name: busslina_dart_web_framework_example
publish_to: none

environment:
  sdk: ^3.3.3

dependencies:
  busslina_dart_web_framework:
    path: ../.
  web: ^0.5.1
  dio: ^5.4.3+1
  rearch: ^1.8.0+0
  synchronized: ^3.1.0+1

dev_dependencies:
  build_runner: ^2.4.9
  build_web_compilers: ^4.0.10
  lints: ^2.1.0
